---

apiVersion: "v1"
kind: "List"
items:

  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
        annotations:
            kubernetes.io/ingress.class: nginx
            kubernetes.io/tls-acme: "#{letsencrypt.enabled}#"
            nginx.ingress.kubernetes.io/client-max-body-size: "500m"
            nginx.ingress.kubernetes.io/proxy-send-timeout: "14400"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "14400"
        name: ingress-#{appname}#-leader
        namespace: #{k8s.namespace}#
    spec:
        rules:
            - host: #{nginx.hostname-leader}# 
              http:
                paths:
                 - backend:
                    serviceName: #{k8s.namespace}#-leader
                    servicePort: 80
                   path: /
        tls:
        - hosts:
          - #{nginx.hostname-leader}#
          secretName: sslcert-leader

  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
        annotations:
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: "#{letsencrypt.enabled}#"
          nginx.ingress.kubernetes.io/client-max-body-size: "500m"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "14400"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "14400"
        name: ingress-#{appname}#
        namespace: #{k8s.namespace}#
    spec:
        rules:
        - host: #{nginx.hostname}# 
          http:
            paths:
              - backend:
                  serviceName: #{k8s.namespace}#
                  servicePort: 80
                path: /
        tls:
        - hosts:
          - #{nginx.hostname}#
          secretName: sslcert
