---
apiVersion: "v1"
kind: "List"
items:
        
  - apiVersion: apps/v1
    kind: "Deployment"
    metadata:
      name: #{k8s.namespace}#-slave
      namespace: #{k8s.namespace}#
    spec:
      replicas: #{k8s.replicas}# # tells deployment to run 1 pod matching the template
      selector:
        matchLabels:
            name: "#{k8s.namespace}#-slave"
            app: "#{k8s.namespace}#"
            containertype: "slave"
      template: # create pods using pod definition in this template
        metadata:
          annotations:
            ad.datadoghq.com/#{k8s.namespace}#-slave.logs: "[{\"source\": \"mendix\", \"service\": \"#{k8s.namespace}#-slave\", \"log_processing_rules\": [{\"type\": \"multi_line\", \"pattern\": \"^(TRACE - |TRACE:|DEBUG - |DEBUG:|INFO - |INFO:|WARNING - |WARNING:|ERROR - |ERROR:|CRITICAL - |CRITICAL:)\", \"name\": \"new_log_start_with_date\"}]}]"
            ad.datadoghq.com/#{k8s.namespace}#-slave.check_names: "[\"prometheus\"]"
            ad.datadoghq.com/#{k8s.namespace}#-slave.init_configs: "[{}]"
            ad.datadoghq.com/#{k8s.namespace}#-slave.instances: "[{\"prometheus_url\": \"http://%%host%%:%%port%%/metrics\",\"namespace\": \"mendix\",\"metrics\": [\"*\"]}]"
            devops_release: "#{Release.DeploymentID}#"
            co.elastic.metrics/hosts: http://${data.host}:${data.ports.metrics}
            co.elastic.metrics/module: prometheus
            co.elastic.metrics/period: 30s
          labels:
            name: "#{k8s.namespace}#-slave"
            app: "#{k8s.namespace}#"
            containertype: "slave"
        spec:
          volumes:
            - name: m2ee-config
              projected:
                sources:
                  - secret:
                      name: m2ee
                      items:
                        - key: adminpassword
                          path: adminpassword
                defaultMode: 420
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: "app"
                        operator: In
                        values:
                        - "#{k8s.namespace}#"
                  topologyKey: "kubernetes.io/hostname"
          automountServiceAccountToken: false
          securityContext:
            runAsNonRoot: true
          imagePullSecrets:
              - name: registry
          containers:
          - name: #{k8s.namespace}#-slave
            securityContext:
               privileged: false
               runAsNonRoot: true
               allowPrivilegeEscalation: false
            image: #{docker.registry}#/#{docker.repository}#/#{appname}#:#{Release.Artifacts.DockerBuild.SourceVersion}#-#{Release.Artifacts.DockerBuild.BuildId}#
            ports:
            - containerPort: 8080
            - containerPort: 9273
            livenessProbe:
               httpGet:
                 path: /
                 port: 8080
               initialDelaySeconds: 90
               periodSeconds: 5
            readinessProbe:
               httpGet:
                 path: /
                 port: 8080
               initialDelaySeconds: 90
               periodSeconds: 5
            resources:
              requests:
                memory: "#{k8s.memoryrequest_slave}#"
            env:
              - name: CF_INSTANCE_INDEX
                value: "1"
              - name: MXRUNTIME_com_mendix_core_StorageService
                value: "#{customruntime.MXRUNTIME_com_mendix_core_StorageService}#"
              - name: MXRUNTIME_com_mendix_storage_azure_AccountName
                value: "#{customruntime.MXRUNTIME_com_mendix_storage_azure_AccountName}#"
              - name: MXRUNTIME_com_mendix_storage_azure_AccountKey
                value: "#{customruntime.MXRUNTIME_com_mendix_storage_azure_AccountKey}#"
              - name: MXRUNTIME_com_mendix_storage_azure_Container
                value: "#{customruntime.MXRUNTIME_com_mendix_storage_azure_Container}#"                
              - name: MXRUNTIME_com_mendix_storage_s3_AccessKeyId
                value: "#{customruntime.MXRUNTIME_com_mendix_storage_s3_AccessKeyId}#"
              - name: MXRUNTIME_com_mendix_storage_s3_SecretAccessKey
                value: "#{customruntime.MXRUNTIME_com_mendix_storage_s3_SecretAccessKey}#"
              - name: MXRUNTIME_com_mendix_storage_s3_BucketName
                value: "#{customruntime.MXRUNTIME_com_mendix_storage_s3_BucketName}#"
              - name: MXRUNTIME_com_mendix_storage_PerformDeleteFromStorage
                value: "false"
              - name: "MXRUNTIME_ApplicationRootUrl"
                value: "#{customruntime.MXRUNTIME_ApplicationUrl}#"
              - name: M2EE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: m2ee
                    key: adminpassword          
            envFrom:
            - configMapRef:
                name: mendix-config
          - name: m2ee-metrics
            image: 'private-cloud.registry.mendix.com/mx-m2ee-metrics:1.1.1'
            args:
              - '-port=9273'
              - '-admin-url=http://localhost:8082'
            ports:
              - name: metrics
                containerPort: 9273
                protocol: TCP
            env:
              - name: MX_APP_ID
                value: #{k8s.namespace}#
            resources:
              limits:
                cpu: 250m
                memory: 32Mi
              requests:
                cpu: 100m
                memory: 16Mi
            volumeMounts:
              - name: m2ee-config
                readOnly: true
                mountPath: /opt/mendix/m2ee
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: Always
            
  - apiVersion: apps/v1
    kind: "Deployment"
    metadata:
      name: #{k8s.namespace}#-leader
      namespace: #{k8s.namespace}#
    spec:
      replicas: 1 # tells deployment to run 1 pod matching the template
      selector:
        matchLabels:
            app: "#{k8s.namespace}#"
            containertype: "leader"
            name: "#{k8s.namespace}#-leader"
      template: # create pods using pod definition in this template
        metadata:
          annotations:  
            ad.datadoghq.com/#{k8s.namespace}#-leader.logs: "[{\"source\": \"mendix\", \"service\": \"#{k8s.namespace}#-leader\", \"log_processing_rules\": [{\"type\": \"multi_line\", \"pattern\": \"^(TRACE - |TRACE:|DEBUG - |DEBUG:|INFO - |INFO:|WARNING - |WARNING:|ERROR - |ERROR:|CRITICAL - |CRITICAL:)\", \"name\": \"new_log_start_with_date\"}]}]"
            ad.datadoghq.com/#{k8s.namespace}#-leader.check_names: "[\"prometheus\"]"
            ad.datadoghq.com/#{k8s.namespace}#-leader.init_configs: "[{}]"
            ad.datadoghq.com/#{k8s.namespace}#-leader.instances: "[{\"prometheus_url\": \"http://%%host%%:%%port%%/metrics\",\"namespace\": \"mendix\",\"metrics\": [\"*\"]}]"
            devops_release: "#{Release.DeploymentID}#"
            co.elastic.metrics/hosts: http://${data.host}:${data.ports.metrics}
            co.elastic.metrics/module: prometheus
            co.elastic.metrics/period: 30s
          labels:
            app: "#{k8s.namespace}#"
            containertype: "leader"
            name: "#{k8s.namespace}#-leader"
        spec:
          volumes:
            - name: m2ee-config
              projected:
                sources:
                  - secret:
                      name: m2ee
                      items:
                        - key: adminpassword
                          path: adminpassword
                defaultMode: 420
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: "app"
                        operator: In
                        values:
                        - "#{k8s.namespace}#"
                  topologyKey: "kubernetes.io/hostname"
          automountServiceAccountToken: false
          securityContext:
            runAsNonRoot: true
          imagePullSecrets:
              - name: registry
          containers:
          - name: #{k8s.namespace}#-leader
            securityContext:
               privileged: false
               runAsNonRoot: true
               allowPrivilegeEscalation: false
            image: #{docker.registry}#/#{docker.repository}#/#{appname}#:#{Release.Artifacts.DockerBuild.SourceVersion}#-#{Release.Artifacts.DockerBuild.BuildId}#
            ports:
            - containerPort: 8080
            - containerPort: 9273
            livenessProbe:
               httpGet:
                 path: /
                 port: 8080
               initialDelaySeconds: 90
               periodSeconds: 5
            readinessProbe:
               httpGet:
                 path: /
                 port: 8080
               initialDelaySeconds: 90
               periodSeconds: 5
               failureThreshold: 120 # high number to accomodate database synchronizations
            resources:
              requests:
                memory: "#{k8s.memoryrequest_leader}#"
            env:
              - name: CF_INSTANCE_INDEX
                value: "0"
              - name: MXRUNTIME_com_mendix_core_StorageService
                value: "#{customruntime.MXRUNTIME_com_mendix_core_StorageService}#"
              - name: MXRUNTIME_com_mendix_storage_azure_AccountName
                value: "#{customruntime.MXRUNTIME_com_mendix_storage_azure_AccountName}#"
              - name: MXRUNTIME_com_mendix_storage_azure_AccountKey
                value: "#{customruntime.MXRUNTIME_com_mendix_storage_azure_AccountKey}#"
              - name: MXRUNTIME_com_mendix_storage_azure_Container
                value: "#{customruntime.MXRUNTIME_com_mendix_storage_azure_Container}#"                
              - name: MXRUNTIME_com_mendix_storage_s3_AccessKeyId
                value: "#{customruntime.MXRUNTIME_com_mendix_storage_s3_AccessKeyId}#"
              - name: MXRUNTIME_com_mendix_storage_s3_SecretAccessKey
                value: "#{customruntime.MXRUNTIME_com_mendix_storage_s3_SecretAccessKey}#"
              - name: MXRUNTIME_com_mendix_storage_s3_BucketName
                value: "#{customruntime.MXRUNTIME_com_mendix_storage_s3_BucketName}#"
              - name: MXRUNTIME_com_mendix_storage_s3_EndPoint  
                value: "#{customruntime.MXRUNTIME_com_mendix_storage_s3_EndPoint}#"
              - name: MXRUNTIME_com_mendix_storage_PerformDeleteFromStorage
                value: "false"
              - name: "MXRUNTIME_ApplicationRootUrl"
                value: "#{customruntime.MXRUNTIME_ApplicationUrl}#"    
              - name: M2EE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: m2ee
                    key: adminpassword
            envFrom:
            - configMapRef:
                name: mendix-config     
          - name: m2ee-metrics
            image: 'private-cloud.registry.mendix.com/mx-m2ee-metrics:1.1.1'
            args:
              - '-port=9273'
              - '-admin-url=http://localhost:8082'
            ports:
              - name: metrics
                containerPort: 9273
                protocol: TCP
            env:
              - name: MX_APP_ID
                value: #{k8s.namespace}#
            resources:
              limits:
                cpu: 250m
                memory: 32Mi
              requests:
                cpu: 100m
                memory: 16Mi
            volumeMounts:
              - name: m2ee-config
                readOnly: true
                mountPath: /opt/mendix/m2ee
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: Always
            
  - apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "#{k8s.namespace}#"
      namespace: "#{k8s.namespace}#"
      labels:
        app: "#{k8s.namespace}#"
    spec:
      selector:
        app: "#{k8s.namespace}#"
      ports:
      - name: http
        port: 80
        targetPort: 8080

  - apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "#{k8s.namespace}#-leader"
      namespace: "#{k8s.namespace}#"
      labels:
        app: "#{k8s.namespace}#-leader"
    spec:
      selector:
        app: "#{k8s.namespace}#"
        containertype: "leader"
      ports:
      - name: http
        port: 80
        targetPort: 8080
        
  - apiVersion: v1
    kind: "Secret"
    metadata:
      name: m2ee
      namespace: "#{k8s.namespace}#"
    data:
      adminpassword: JHd1OTVMRW5JQDQ9OVdXdA==
    type: Opaque

